[colors.bright]
black = "#767676"
blue = "#1a8fff"
cyan = "#14ffff"
green = "#00A600"
magenta = "#fd28ff"
red = "#f2201f"
white = "#100000"
yellow = "#fffd00"

[colors.cursor]
background = "#000000"
foreground = "#ffffff"

[cursor.style]
shape = "Beam"

[colors.normal]
black = "#000000"
blue = "#0d73cc"
cyan = "#0dcdcd"
green = "#19cb00"
magenta = "#cb1ed1"
red = "#cc0403"
white = "#dddddd"
yellow = "#cecb00"

[colors.primary]
background = "#FAF2EB"
foreground = "#000000"

[env]
TERM = "xterm-256color"

[font]
size = 13.5

[font.offset]
y = 1

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "regular"

[window]
decorations = "None"

[window.padding]
x = 25
y = 18
