#!/bin/bash

alias la='ls -vla' 
alias l='ls -AH'
alias c='clear'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -ir'
alias b='cd - >/dev/null'
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias dot="cd ~/.dotfiles"
alias tam='tmux attach -t main'
alias tnm='tmux new -s main'
alias tks='tmux kill-server'
alias n='nvim'
alias ntrash='cd ~/.local/share/nvim/mini.files/trash'
alias py='python3'
alias pip='pip3'
alias path='echo -e ${PATH//:/\\n}'
alias week='date +%V'
alias g='git'
alias cpath='pwd | pbcopy'
