#!/bin/bash

# Source settings
source ~/.dotfiles/shell/functions
source ~/.dotfiles/shell/prompt
source ~/.dotfiles/shell/aliases
source ~/.dotfiles/shell/options
source ~/.dotfiles/shell/fzf
source ~/.dotfiles/shell/less

# Start PDF script in background
dpdf &
