#!/bin/bash

# Source settings
source ~/.dotfiles/shell/functions
source ~/.dotfiles/shell/prompt
source ~/.dotfiles/shell/aliases
source ~/.dotfiles/shell/options

# Start PDF script in background
dpdf &
