#!/bin/bash

# Path variables
PATH=~/.dotfiles/scripts/:$PATH
PATH=/opt/homebrew/opt/fzf/bin:$PATH
PATH=/opt/homebrew/bin:$PATH

#Environment Variables
export EDITOR="nvim"
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_STATE_HOME=$HOME/.local/state

# Source
source "$HOME/.bashrc"
