#!/bin/bash

function ff(){
  fd_options=(--hidden --follow --color always)
  exclude_dirs=(
    Library
    Music
    Movies
    automatic_backups
    Public
    Desktip
    Applications
    Pictures
    .cache
    .local
    .m2
    .idlerc
    .Trash
    .Applications
    .ssh
    .vscode
    .config
    .DS_Store
    .npm
    .git
    .matplotlib
    .cups
    .cargo
    .swiftpm
  )

  for dir in "${exclude_dirs[@]}"; do
    fd_options+=(--exclude "$dir")
  done

  selected_raw=$(fd "${fd_options[@]}" | fzf-tmux -p60%,35% --ansi)
  if [ -z "$selected_raw" ]; then return 0; fi

  selected_dir=$(realpath "${selected_raw%/*}")
  selected_file=$(basename "$selected_raw")
  last_char=${selected_raw: -1}

  if [ "$last_char" = '/' ]; then
    cd "$selected_dir" 
  else 
    cd "$selected_dir" 2>/dev/null
    case $(file --mime-type "$selected_file" -bL) in text/*|application/json) 
    $EDITOR "$selected_file";; *) 
    open "$selected_file" ;; 
    esac
  fi
}
bind '"\C-f":"\C-uff\n"'

function mcdir() {
  mkdir "$1" && cd "$1"
}
