#!/bin/bash

function ff(){
  fd_options=(--hidden --follow --color always)
  exclude_dirs=(
    Library
    Music
    Movies
    Public
    Desktip
    Applications
    Pictures
    automatic_backups
    .cache
    .local
    .m2
    .idlerc
    .Trash
    .Applications
    .ssh
    .vscode
    .config
    .DS_Store
    .npm
    .git
    .matplotlib
    .cups
    .cargo
    .swiftpm
  )

  for dir in "${exclude_dirs[@]}"; do
    fd_options+=(--exclude "$dir")
  done

  selected=$(fd "${fd_options[@]}" | fzf-tmux -p60%,35% --ansi)
  if [ -z "$selected" ]; then return; fi

  filetype=$(file --mime-type -b "$selected")

  if [[ $filetype == "inode/directory" ]]; then
      cd "$selected" || return
  elif [[ $filetype == text/* || $filetype == application/json || $filetype == inode/x-empty ]]; then
      cd "$(dirname "$selected")" || return
      $EDITOR "$(basename "$selected")"
  else
      cd "$(dirname "$selected")" || return
      open "$(basename "$selected")"
  fi
}
bind '"\C-f":"\C-uff\n"'

function mcdir() {
  mkdir "$1"
  cd "$1" || return
}
