#!/bin/bash

function ff(){
  fd_options=( --hidden --follow --color always --exclude Library --exclude Music --exclude Movies --exclude automatic_backups --exclude Public --exclude Desktip --exclude Applications --exclude Pictures --exclude .cache --exclude .local --exclude .m2 --exclude .idlerc --exclude .Trash --exclude .Applications --exclude .ssh --exclude .vscode --exclude .config --exclude .DS_Store --exclude .npm --exclude .git --exclude .matplotlib --exclude .cups --exclude .cargo --exclude .swiftpm)

  selected_raw=$(fd "${fd_options[@]}" | fzf-tmux -p60% --ansi)
  if [ -z "$selected_raw" ]; then return 0; fi

  selected_dir=$(realpath "${selected_raw%/*}")
  selected_file=$(basename "$selected_raw")
  last_char=${selected_raw: -1}

  if [ "$last_char" = '/' ]; then
    cd "$selected_dir" 
  else 
    cd "$selected_dir" 2>/dev/null
    case $(file --mime-type "$selected_file" -bL) in text/*|application/json) 
    $EDITOR "$selected_file";; *) 
    open "$selected_file" ;; 
    esac
  fi
}
bind '"\C-f":"\C-uff\n"'

function mcdir() {
  mkdir "$1" && cd "$1"
}
