#!/bin/bash

# History
HISTSIZE=1048576
HISTFILESIZE=$HISTSIZE
HISTFILE=$XDG_STATE_HOME/bash/history
HISTCONTROL=ignoreboth:erasedups
shopt -s histappend

# Colors (https://geoff.greer.fm/lscolors/)
export CLICOLOR=
export LSCOLORS='exfxcxdxbxegedabagacad' 

# Setup FZF
export FZF_DEFAULT_OPTS="
  --layout=reverse
  --color hl:011,fg+:015,bg+:-1,hl+:011
  --prompt='❯ '
  --pointer='▶'
  --marker='│'
"
export FZF_TMUX_OPTS='-p50%'
source "/opt/homebrew/opt/fzf/shell/completion.bash"
source "/opt/homebrew/opt/fzf/shell/key-bindings.bash"

# Unknown locale, assuming C error
export LANG="en_US.UTF-8"

# Less 
export LESSHISTFILE=-
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'
