#!/bin/bash

# git clone $url && cd .dotfiles && ./install

DOTFILES_LOCATION="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -s "$DOTFILES_LOCATION"/vimrc ~/.vimrc
ln -s "$DOTFILES_LOCATION"/shell/bashrc ~/.bashrc
ln -s "$DOTFILES_LOCATION"/shell/inputrc ~/.inputrc
ln -s "$DOTFILES_LOCATION"/shell/alacritty ~/.config/alacritty
ln -s "$DOTFILES_LOCATION"/shell/git ~/.config/git
ln -s "$DOTFILES_LOCATION"/shell/karabiner ~/.config/karabiner
ln -s "$DOTFILES_LOCATION"/shell/sketchybar ~/.config/sketchybar
ln -s "$DOTFILES_LOCATION"/shell/nvim ~/.config/nvim
ln -s "$DOTFILES_LOCATION"/shell/skhd ~/.config/skhd
ln -s "$DOTFILES_LOCATION"/shell/tmux ~/.config/tmux
ln -s "$DOTFILES_LOCATION"/shell/yabai ~/.config/yabai
