#!/usr/bin/bash

start_listener(){
    wl_pid=$(ps -eo pid,args | grep "[w]l-paste --watch" | awk '{print $1}')
    if [ -z "$wl_pid" ]; then
        echo "Starting new clipman process"
        wl-paste --watch clipman
    else
        echo "Already ongoing clipman process"
    fi
}

update_history(){
    item=$(wl-paste)
    notify-send -t 1000 "$item"
}

