#!/usr/bin/env bash

selected=$(man -k . | grep -v "([0-9]p)" | sed 's/ - .*//' | sort | fzf-tmux --border-label "MANPAGES" -p40%)
name=$(echo "$selected" | sed -n 's/^\(.*\) ([0-9]\+).*/\1/p')
section=$(echo "$selected" | sed -n 's/.*(\([0-9]\+\)).*/\1/p')

man "$section" "$name"
