#!/bin/bash

pid=$(swaymsg -t get_tree | jq '.. | select(.type?) | select(.focused==true).pid')
process=$(ps -q "$pid" -o args=)
application=$(echo "$process" | awk '{print $1}')
arg=$(echo "$process" | awk '{print $2}')

if [[ "$application" != "zathura" ]]; then
    notify-send -t 5000 "$application"
    notify-send -t 5000 "not zathura"
    exit 1
fi

pdf_name=$(yad --entry \
    --text="New pdf name:" \
    --entry-text="" \
    --width=300 \
    --height=100 \
    --no-buttons)

new_file=/home/schnei/Downloads/"$pdf_name"
mv "$arg" "$new_file"
kill "$pid"
zathura "$new_file"
