#!/usr/bin/env bash

read -p "What host would you like to transfer the files to? " remote_host

files_to_transfer=(
  ~/.dotfiles/shell/inputrc
  ~/.dotfiles/shell/aliases
  ~/.dotfiles/shell/functions
  ~/.dotfiles/vimrc
)

scp "${files_to_transfer[@]}" "$remote_host:~/.dotfiles"

#Make symlinks to right place
files="basename
