# Set the ZDOTDIR and ZSH environment variable
export ZDOTDIR="${HOME}/.config/zsh"

#Set different variables
export EDITOR="nvim"

#Dont make a .lesshst file
export LESSHISTFILE=-

# Set the XDG_*_HOME environment variables
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_STATE_HOME="${HOME}/.local/state"

# Set the location of the command history file
export HISTFILE="${ZDOTDIR}/.zsh_history"

#Move ~/.python_history to XDG_CACHE_HOME
export PYTHONPYCACHEPREFIX=$XDG_CACHE_HOME/python
