# Created by Zap installer
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

# Load and initialise completion system
autoload -Uz compinit && compinit

#Plugins
plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-syntax-highlighting"
plug "Aloxaf/fzf-tab"
plug "ael-code/zsh-colored-man-pages"

#Local files
source ~/.dotfiles/shell/aliases.sh
source ~/.dotfiles/shell/nav.sh
source ~/.dotfiles/shell/functions.sh

#Bind Ctrl+F to the ff script
function nav-widget {
  nav
  local precmd
  for precmd in $precmd_functions; do
    $precmd
  done
  zle reset-prompt
}
zle -N nav-widget
bindkey "^f" nav-widget

#FZF
export FZF_DEFAULT_OPTS="--layout=reverse"
export FZF_TMUX_OPTS="-p60%"

#Options
setopt autocd
KEYTIMEOUT=1

# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

[ -f ~/.config/zsh/.fzf.zsh ] && source ~/.config/zsh/.fzf.zsh

# Setting up prompt
eval "$(starship init zsh)"
